### ISSUE TITLE
1st online meeting 

### ISSUE THREAD

**Issue by ariestiyansyah** [ionicindonesia/meetup#1]
Berikut adalah detail untuk online meeting ionic indonesia:

Date/Time: 
Sabtu, February 6, 2016, start 10pm 

Lokasi: Google Hangout (https://hangouts.google.com/call/p2lwn7b6wmi7upr7nvjtdjodwma)

Agenda:
- ionic indonesia website
- offline meetup
- ionic indonesia community directory

Goal:

Strategies:

Jika ada tambahan silahkan berikan komentar.

**Comment by kalingga** [comment]
Memantau dulu mas. ditunggu teman-teman yang lainnya. semoga sukses 1st meetup ini...

**Comment by takujeng** [comment]
pengen ikutan, tapi dah balik Surabaya. Yang di Surabaya boleh deh buat pertemuan serupa

**Comment by RizRiyz** [comment]
@takujeng ini kan online jadi darimanapun bisa ikut :)

**Comment by takujeng** [comment]
ya, baru nyadar waktu lihat lokasinya google hangout :)

**Comment by RizRiyz** [comment]
Update Google Docs untul live meeting: https://docs.google.com/document/d/1exYzLuDtTesIXdmfSqXvac60kg953lybXfOlQLVER8Y/edit?usp=sharing
